<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Joaoaalves.Queues\Joaoaalves.Queues.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Joaoaalves.Queues.Notifications.SignalR</PackageId>
    <Version>0.0.0</Version>
    <Authors>João Alves</Authors>
    <Company>João Alves</Company>
    <Description>Add SignalR implementations for Joaoaalves.Queues.Abstractions library.</Description>
    <PackageTags>Queues; SignalR;</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <RepositoryUrl>https://github.com/Joaoaalves/dotnet-queues</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Joaoaalves/dotnet-queues</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
