<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Joaoaalves.Queues.Abstractions\Joaoaalves.Queues.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Joaoaalves.Queues</PackageId>
    <Version>0.0.0</Version>
    <Authors>João Alves</Authors>
    <Company>João Alves</Company>
    <Description>Add default implementations for Joaoaalves.Queues.Abstractions library.</Description>
    <PackageTags>Queues;</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <RepositoryUrl>https://github.com/Joaoaalves/dotnet-queues</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Joaoaalves/dotnet-queues</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
